# Generated by Django 2.1.5 on 2019-01-30 11:20

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('user_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('time_published', models.FloatField(default=1548847238.060685)),
                ('text', models.TextField()),
                ('room', models.TextField()),
            ],
        ),
    ]
