"""
Django settings for financechat project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i-pe2nm4&9ch7ui6a01jr_dt%l)kh*u#88ig!(cmhw+9h+o83l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

RMQ_SETTINGS = {
    'RMQ_HOST': os.environ.get('RMQ_HOST', 'localhost'),
    'RMQ_USER': os.environ.get('RMQ_USER', 'guest'),
    'RMQ_PASS': os.environ.get('RMQ_PASS', 'guest'),
}

# To execute RabbitMQ with Docker: docker run --rm -it -p 5672:5672 rabbitmq:3.7.8-alpine

DB_SETTINGS = {
    'USER': os.environ.get('DB_USER', 'test'),
    'PASSWORD': os.environ.get('DB_PASS', 'test1234'),
    'NAME': os.environ.get('DB_NAME', 'financechat'),
    'HOST': os.environ.get('DB_HOST', 'ds227185.mlab.com'),
    'PORT': os.environ.get('DB_PORT', 27185),
    'ENGINE': 'djongo',
    'AUTH_SOURCE': 'financechat',
    'AUTH_MECHANISM': 'SCRAM-SHA-1'
}

# DjongoClient.enforce_schema = False

# Application definition

INSTALLED_APPS = [
    'channels',
    'chatroom',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": "amqp://{RMQ_USER}:{RMQ_PASS}@{RMQ_HOST}/".format(**RMQ_SETTINGS),
        },
    },
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'financechat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'financechat.wsgi.application'
ASGI_APPLICATION = 'financechat.routing.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': DB_SETTINGS

}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/chatroom/'

LOGOUT_REDIRECT_URL = '/'
